remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Cloning and fast synchronizing block devices using a digest file
description: Cloning and fast synchronizing block devices using a digest file

show_downloads: true
google_analytics: G-2R5ELGM39X
