#!/bin/bash

# ./scripts/example-volume1-backup - this file is a part of program blocksync-fast

# Copyright (C) 2024 Marcin Koczwara <mk@nethorizon.pl>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# START SETTINGS

VG='vg1'
LV='volume1'

SNAP_NAME='snap-backup'
SNAP_SIZE='5G'

DIGEST_PATH="/var/db/blocksync/$LV.digest"
DESTDIR="/mnt/backups"

ROTATE_DAYS=7
ROTATE_WEEKS=4
ROTATE_MONTHS=0

# END SETTINGS

source ./gfs-lvm-backup.sh
