#!/bin/bash

# START SETTINGS

VG='vg1'
LV='volume1'

SNAP_NAME='snap-backup'
SNAP_SIZE='5G'

DIGEST_PATH="/var/db/blocksync/$LV.digest"
DESTDIR="/mnt/backups"

ROTATE_DAYS=7
ROTATE_WEEKS=4
ROTATE_MONTHS=0

# END SETTINGS

YEAR=$(date +%Y)
MONTH=$(date +%m)
DAY_OF_MONTH=$(date +%d)
DAY_OF_WEEK=$(date +%u)
HOUR=$(date +%H)
MINUTE=$(date +%M)

BACKUPTIME="$YEAR-$MONTH-${DAY_OF_MONTH}_$HOUR:$MINUTE"


export PATH=$PATH:/usr/local/bin:/usr/local/sbin

mountDstDir()
{
    sync;
    (mount | grep $DESTDIR  > /dev/null 2>&1) || (mount $DESTDIR)
    if [ "$?" != "0" ]; then
	logger "$0 - $DESTDIR not mounted";
	exit 1;
    fi
}



createSnapshot()
{
    sync;
    (lvcreate -L$SNAP_SIZE -s -n $LV-$SNAP_NAME $VG/$LV > /dev/null 2>&1)
    if [ "$?" != "0" ]; then
	logger "$0 - creating snapshot $VG/$LV-$SNAP_NAME failed";
	exit 1;
    fi
}


removeSnapshot()
{
    sync;
    [ ! -e "/dev/$VG/$LV-$SNAP_NAME" ] || (lvremove -f $VG/$LV-$SNAP_NAME > /dev/null 2>&1)
    if [ "$?" != "0" ]; then
	logger "$0 - removing snapshot $VG/$LV-$SNAP_NAME failed";
	exit 1;
    fi
}

makeBackup()
{
    sync;
    [ -d "$DESTDIR/$LV" ] || (mkdir "$DESTDIR/$LV" > /dev/null 2>&1)
    LOG=$(blocksync --src=/dev/$VG/$LV-$SNAP_NAME --dst=$DESTDIR/$LV/current --digest=$DIGEST_PATH)

    if [ "$?" != "0" ]; then
	logger "$0 - creating backup failed";
    else
        echo $(date) > "$DESTDIR/$LV/current.date"
	logger "$0 - blocksync $VG/$LV : $LOG";
    fi;
}


rotateBackupDaily()
{
    if [ $ROTATE_DAYS -gt 0 ]; then
    
        [ -d "$DESTDIR/$LV/daily" ] || (mkdir "$DESTDIR/$LV/daily" > /dev/null 2>&1)
	cp --reflink "$DESTDIR/$LV/current" "$DESTDIR/$LV/daily/$LV-$BACKUPTIME"
	
	i=0
	
	for x in $(ls $DESTDIR/$LV/daily | sort -r); do

	    if [ $i -ge $ROTATE_DAYS ]; then
		rm "$DESTDIR/$LV/daily/$x"
	    fi
	    ((i++))
	done;
    fi;
}

rotateBackupWeekly()
{
    if [ $ROTATE_WEEKS -gt 0 ] && [ $DAY_OF_WEEK -eq 1 ]; then
    
        [ -d "$DESTDIR/$LV/weekly" ] || (mkdir "$DESTDIR/$LV/weekly" > /dev/null 2>&1)
	cp --reflink "$DESTDIR/$LV/current" "$DESTDIR/$LV/weekly/$LV-$BACKUPTIME"
	
	i=0
	
	for x in $(ls $DESTDIR/$LV/weekly | sort -r); do

	    if [ $i -ge $ROTATE_WEEKS ]; then
		rm "$DESTDIR/$LV/weekly/$x"
	    fi
	    ((i++))
	done;
    fi;
}

rotateBackupMonthly()
{
    if [ $ROTATE_MONTHS -gt 0 ] && [ $DAY_OF_MONTH -eq 1 ]; then
    
        [ -d "$DESTDIR/$LV/monthly" ] || (mkdir "$DESTDIR/$LV/monthly" > /dev/null 2>&1)
	cp --reflink "$DESTDIR/$LV/current" "$DESTDIR/$LV/monthly/$LV-$BACKUPTIME"
	
	i=0
	
	for x in $(ls $DESTDIR/$LV/monthly | sort -r); do

	    if [ $i -ge $ROTATE_MONTHS ]; then
		rm "$DESTDIR/$LV/monthly/$x"
	    fi
	    ((i++))
	done;
    fi;
}


removeSnapshot;
mountDstDir;
createSnapshot;
makeBackup;
removeSnapshot;

rotateBackupDaily;
rotateBackupWeekly;
rotateBackupMonthly;
